# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Efficiently computes X' * W * X where W is a diagonal matrix.
NULL

arma_XTWX <- function(X, W_diag) {
    .Call(`_glmModel_arma_XTWX`, X, W_diag)
}

